version: 2
before:
  hooks:
    - make release-manifests-build

builds:
  - id: kubectl-moco
    main: ./cmd/kubectl-moco
    binary: kubectl-moco
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore: # ref: https://goreleaser.com/deprecations/#builds-for-windowsarm64
      - goos: windows
        goarch: arm64

archives:
  - ids:
      - kubectl-moco
    name_template: "kubectl-{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    formats: ['tar.gz']
    files:
      - LICENSE

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  github:
    owner: cybozu-go
    name: moco
  prerelease: auto
  name_template: "Release {{ .Tag }}"
  footer: |
    See [CHANGELOG.md](./CHANGELOG.md) for details.
  extra_files:
    - glob: build/moco.yaml
