name: Integration tests with MySQL
description: 'An action to run integration tests with MySQL'

inputs:
  mysql-version:
    description: 'MySQL version'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - name: Setup Aqua
      uses: ./.github/actions/setup-aqua
    - run: make setup
      shell: bash
    - run: make test-bkop MYSQL_VERSION=${{ inputs.mysql-version }}
      shell: bash
    - run: make test-dbop MYSQL_VERSION=${{ inputs.mysql-version }}
      shell: bash
