---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-moco-cybozu-com-v1beta2-mysqlcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mmysqlcluster.kb.io
  rules:
  - apiGroups:
    - moco.cybozu.com
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    resources:
    - mysqlclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-moco-cybozu-com-v1beta2-backuppolicy
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vbackuppolicy.kb.io
  rules:
  - apiGroups:
    - moco.cybozu.com
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - backuppolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-moco-cybozu-com-v1beta2-mysqlcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vmysqlcluster.kb.io
  rules:
  - apiGroups:
    - moco.cybozu.com
    apiVersions:
    - v1beta2
    operations:
    - CREATE
    - UPDATE
    resources:
    - mysqlclusters
  sideEffects: None
