apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "moco.fullname" . }}-grpc-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moco.labels" . | nindent 4 }}
spec:
  ca:
    secretName: moco-grpc-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "moco.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moco.labels" . | nindent 4 }}
spec:
  selfSigned: {}
