resources:
  - ../../../rbac
  - ../../../webhook

namespace: '{{ .Release.Namespace }}'

namePrefix: 'moco-'

commonLabels:
  app.kubernetes.io/name: '{{ include "moco.name" . }}'

patchesStrategicMerge:
  - webhookcainjection-patch.yaml

transformers:
  - label-transformer.yaml
