resources:
  - ../../../rbac
  - ../../../webhook

namespace: '{{ .Release.Namespace }}'

namePrefix: 'moco-'

commonLabels:
  app.kubernetes.io/name: '{{ include "moco.name" . }}'

patchesStrategicMerge:
  - webhookcainjection-patch.yaml

transformers:
  - label-transformer.yaml

patches:
  - target:
      group: admissionregistration.k8s.io
      version: v1beta1
      kind: 'ValidatingAdmissionPolicy|ValidatingAdmissionPolicyBinding'
      name: '.*'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: '{{ include "admissionregistration.apiVersion" . }}'
