apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../rbac
- ../../../webhook

namespace: '{{ .Release.Namespace }}'

namePrefix: moco-

labels:
- pairs:
    app.kubernetes.io/name: '{{ include "moco.name" . }}'
  includeSelectors: true

patches:
- path: webhookcainjection-patch.yaml

transformers:
- label-transformer.yaml
