#!/bin/sh -e

if [ $# -eq 0 ]; then
    echo "Usage: tag_exists NAME"
    exit 1
fi

NAME="$1"
if [ $# -eq 2 ]; then
    DIR="$2"
else
    DIR="$NAME"
fi
TAG=$(cat "$DIR"/TAG)

TOKEN=$(curl -sSfL https://ghcr.io/token\?scope="repository:cybozu-go/moco:pull" | jq -r .token)
HTTP_STATUS=$(curl --head -H "Authorization: Bearer $TOKEN" -sSL -w "%{http_code}" "https://ghcr.io/v2/cybozu-go/moco/$NAME/manifests/$TAG" -o /dev/null)

if [ "$HTTP_STATUS" = "404" ]; then
    echo "ok"
    exit 0
fi

echo "ng"
