# permissions for end users to edit mysqlclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlcluster-editor-role
rules:
- apiGroups:
  - myso.cybozu.com
  resources:
  - mysqlclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myso.cybozu.com
  resources:
  - mysqlclusters/status
  verbs:
  - get
