apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: azurite
spec:
  ports:
    - name: blob
      port: 10000
      targetPort: blob
      protocol: TCP
  selector:
    name: azurite
---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: azurite
  labels:
    name: azurite
spec:
  containers:
    - name: azurite
      image: mcr.microsoft.com/azure-storage/azurite
      args:
        - "azurite-blob"
        - "--blobHost=0.0.0.0"
        - "--blobPort=10000"
        - "--location=/data"
        - "--skipApiVersionCheck"
        - "--loose"
        - "--disableProductStyleUrl"
      # env:
      #   - name: AZURITE_ACCOUNTS
      #     value: "devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
      ports:
        - name: blob
          containerPort: 10000
          protocol: TCP
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      emptyDir: {}
