apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
featureGates:
  ValidatingAdmissionPolicy: true
runtimeConfig:
  admissionregistration.k8s.io/v1beta1: true
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
