apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../crd

patches:
  - path: conversion-patch.yaml

commonLabels:
  app.kubernetes.io/name: moco

commonAnnotations:
  helm.sh/resource-policy: keep

transformers:
  - label-transformer.yaml
