apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../crd

patches:
- path: conversion-patch.yaml

labels:
- pairs:
    app.kubernetes.io/name: moco
  includeSelectors: true

commonAnnotations:
  helm.sh/resource-policy: keep

transformers:
- label-transformer.yaml
