//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1beta2 "github.com/cybozu-go/moco/api/v1beta2"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
	applyconfigurationsmetav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AffinityApplyConfiguration)(nil), (*v1beta2.AffinityApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__AffinityApplyConfiguration_To_v1beta2_AffinityApplyConfiguration(a.(*AffinityApplyConfiguration), b.(*v1beta2.AffinityApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.AffinityApplyConfiguration)(nil), (*AffinityApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_AffinityApplyConfiguration_To__AffinityApplyConfiguration(a.(*v1beta2.AffinityApplyConfiguration), b.(*AffinityApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BackupPolicy)(nil), (*v1beta2.BackupPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__BackupPolicy_To_v1beta2_BackupPolicy(a.(*BackupPolicy), b.(*v1beta2.BackupPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BackupPolicy)(nil), (*BackupPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BackupPolicy_To__BackupPolicy(a.(*v1beta2.BackupPolicy), b.(*BackupPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BackupPolicyList)(nil), (*v1beta2.BackupPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__BackupPolicyList_To_v1beta2_BackupPolicyList(a.(*BackupPolicyList), b.(*v1beta2.BackupPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BackupPolicyList)(nil), (*BackupPolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BackupPolicyList_To__BackupPolicyList(a.(*v1beta2.BackupPolicyList), b.(*BackupPolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BackupPolicySpec)(nil), (*v1beta2.BackupPolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__BackupPolicySpec_To_v1beta2_BackupPolicySpec(a.(*BackupPolicySpec), b.(*v1beta2.BackupPolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BackupPolicySpec)(nil), (*BackupPolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BackupPolicySpec_To__BackupPolicySpec(a.(*v1beta2.BackupPolicySpec), b.(*BackupPolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BackupStatus)(nil), (*v1beta2.BackupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__BackupStatus_To_v1beta2_BackupStatus(a.(*BackupStatus), b.(*v1beta2.BackupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BackupStatus)(nil), (*BackupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BackupStatus_To__BackupStatus(a.(*v1beta2.BackupStatus), b.(*BackupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BucketConfig)(nil), (*v1beta2.BucketConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__BucketConfig_To_v1beta2_BucketConfig(a.(*BucketConfig), b.(*v1beta2.BucketConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.BucketConfig)(nil), (*BucketConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_BucketConfig_To__BucketConfig(a.(*v1beta2.BucketConfig), b.(*BucketConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnvFromSourceApplyConfiguration)(nil), (*v1beta2.EnvFromSourceApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__EnvFromSourceApplyConfiguration_To_v1beta2_EnvFromSourceApplyConfiguration(a.(*EnvFromSourceApplyConfiguration), b.(*v1beta2.EnvFromSourceApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EnvFromSourceApplyConfiguration)(nil), (*EnvFromSourceApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EnvFromSourceApplyConfiguration_To__EnvFromSourceApplyConfiguration(a.(*v1beta2.EnvFromSourceApplyConfiguration), b.(*EnvFromSourceApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EnvVarApplyConfiguration)(nil), (*v1beta2.EnvVarApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__EnvVarApplyConfiguration_To_v1beta2_EnvVarApplyConfiguration(a.(*EnvVarApplyConfiguration), b.(*v1beta2.EnvVarApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EnvVarApplyConfiguration)(nil), (*EnvVarApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EnvVarApplyConfiguration_To__EnvVarApplyConfiguration(a.(*v1beta2.EnvVarApplyConfiguration), b.(*EnvVarApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JobConfig)(nil), (*v1beta2.JobConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__JobConfig_To_v1beta2_JobConfig(a.(*JobConfig), b.(*v1beta2.JobConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.JobConfig)(nil), (*JobConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_JobConfig_To__JobConfig(a.(*v1beta2.JobConfig), b.(*JobConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MySQLClusterCondition)(nil), (*v1beta2.MySQLClusterCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__MySQLClusterCondition_To_v1beta2_MySQLClusterCondition(a.(*MySQLClusterCondition), b.(*v1beta2.MySQLClusterCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.MySQLClusterCondition)(nil), (*MySQLClusterCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MySQLClusterCondition_To__MySQLClusterCondition(a.(*v1beta2.MySQLClusterCondition), b.(*MySQLClusterCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MySQLClusterList)(nil), (*v1beta2.MySQLClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__MySQLClusterList_To_v1beta2_MySQLClusterList(a.(*MySQLClusterList), b.(*v1beta2.MySQLClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.MySQLClusterList)(nil), (*MySQLClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MySQLClusterList_To__MySQLClusterList(a.(*v1beta2.MySQLClusterList), b.(*MySQLClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MySQLClusterStatus)(nil), (*v1beta2.MySQLClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__MySQLClusterStatus_To_v1beta2_MySQLClusterStatus(a.(*MySQLClusterStatus), b.(*v1beta2.MySQLClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.MySQLClusterStatus)(nil), (*MySQLClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MySQLClusterStatus_To__MySQLClusterStatus(a.(*v1beta2.MySQLClusterStatus), b.(*MySQLClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectMeta)(nil), (*v1beta2.ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__ObjectMeta_To_v1beta2_ObjectMeta(a.(*ObjectMeta), b.(*v1beta2.ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.ObjectMeta)(nil), (*ObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ObjectMeta_To__ObjectMeta(a.(*v1beta2.ObjectMeta), b.(*ObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersistentVolumeClaim)(nil), (*v1beta2.PersistentVolumeClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__PersistentVolumeClaim_To_v1beta2_PersistentVolumeClaim(a.(*PersistentVolumeClaim), b.(*v1beta2.PersistentVolumeClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.PersistentVolumeClaim)(nil), (*PersistentVolumeClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PersistentVolumeClaim_To__PersistentVolumeClaim(a.(*v1beta2.PersistentVolumeClaim), b.(*PersistentVolumeClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PersistentVolumeClaimSpecApplyConfiguration)(nil), (*v1beta2.PersistentVolumeClaimSpecApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__PersistentVolumeClaimSpecApplyConfiguration_To_v1beta2_PersistentVolumeClaimSpecApplyConfiguration(a.(*PersistentVolumeClaimSpecApplyConfiguration), b.(*v1beta2.PersistentVolumeClaimSpecApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.PersistentVolumeClaimSpecApplyConfiguration)(nil), (*PersistentVolumeClaimSpecApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PersistentVolumeClaimSpecApplyConfiguration_To__PersistentVolumeClaimSpecApplyConfiguration(a.(*v1beta2.PersistentVolumeClaimSpecApplyConfiguration), b.(*PersistentVolumeClaimSpecApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PodSpecApplyConfiguration)(nil), (*v1beta2.PodSpecApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__PodSpecApplyConfiguration_To_v1beta2_PodSpecApplyConfiguration(a.(*PodSpecApplyConfiguration), b.(*v1beta2.PodSpecApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.PodSpecApplyConfiguration)(nil), (*PodSpecApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PodSpecApplyConfiguration_To__PodSpecApplyConfiguration(a.(*v1beta2.PodSpecApplyConfiguration), b.(*PodSpecApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PodTemplateSpec)(nil), (*v1beta2.PodTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__PodTemplateSpec_To_v1beta2_PodTemplateSpec(a.(*PodTemplateSpec), b.(*v1beta2.PodTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReconcileInfo)(nil), (*v1beta2.ReconcileInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__ReconcileInfo_To_v1beta2_ReconcileInfo(a.(*ReconcileInfo), b.(*v1beta2.ReconcileInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.ReconcileInfo)(nil), (*ReconcileInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ReconcileInfo_To__ReconcileInfo(a.(*v1beta2.ReconcileInfo), b.(*ReconcileInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RestoreSpec)(nil), (*v1beta2.RestoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__RestoreSpec_To_v1beta2_RestoreSpec(a.(*RestoreSpec), b.(*v1beta2.RestoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.RestoreSpec)(nil), (*RestoreSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_RestoreSpec_To__RestoreSpec(a.(*v1beta2.RestoreSpec), b.(*RestoreSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceSpecApplyConfiguration)(nil), (*v1beta2.ServiceSpecApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__ServiceSpecApplyConfiguration_To_v1beta2_ServiceSpecApplyConfiguration(a.(*ServiceSpecApplyConfiguration), b.(*v1beta2.ServiceSpecApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.ServiceSpecApplyConfiguration)(nil), (*ServiceSpecApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ServiceSpecApplyConfiguration_To__ServiceSpecApplyConfiguration(a.(*v1beta2.ServiceSpecApplyConfiguration), b.(*ServiceSpecApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceTemplate)(nil), (*v1beta2.ServiceTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__ServiceTemplate_To_v1beta2_ServiceTemplate(a.(*ServiceTemplate), b.(*v1beta2.ServiceTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.ServiceTemplate)(nil), (*ServiceTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ServiceTemplate_To__ServiceTemplate(a.(*v1beta2.ServiceTemplate), b.(*ServiceTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VolumeApplyConfiguration)(nil), (*v1beta2.VolumeApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__VolumeApplyConfiguration_To_v1beta2_VolumeApplyConfiguration(a.(*VolumeApplyConfiguration), b.(*v1beta2.VolumeApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.VolumeApplyConfiguration)(nil), (*VolumeApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_VolumeApplyConfiguration_To__VolumeApplyConfiguration(a.(*v1beta2.VolumeApplyConfiguration), b.(*VolumeApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VolumeMountApplyConfiguration)(nil), (*v1beta2.VolumeMountApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__VolumeMountApplyConfiguration_To_v1beta2_VolumeMountApplyConfiguration(a.(*VolumeMountApplyConfiguration), b.(*v1beta2.VolumeMountApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.VolumeMountApplyConfiguration)(nil), (*VolumeMountApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_VolumeMountApplyConfiguration_To__VolumeMountApplyConfiguration(a.(*v1beta2.VolumeMountApplyConfiguration), b.(*VolumeMountApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VolumeSourceApplyConfiguration)(nil), (*v1beta2.VolumeSourceApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__VolumeSourceApplyConfiguration_To_v1beta2_VolumeSourceApplyConfiguration(a.(*VolumeSourceApplyConfiguration), b.(*v1beta2.VolumeSourceApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.VolumeSourceApplyConfiguration)(nil), (*VolumeSourceApplyConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_VolumeSourceApplyConfiguration_To__VolumeSourceApplyConfiguration(a.(*v1beta2.VolumeSourceApplyConfiguration), b.(*VolumeSourceApplyConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*MySQLClusterSpec)(nil), (*v1beta2.MySQLClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__MySQLClusterSpec_To_v1beta2_MySQLClusterSpec(a.(*MySQLClusterSpec), b.(*v1beta2.MySQLClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*MySQLCluster)(nil), (*v1beta2.MySQLCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert__MySQLCluster_To_v1beta2_MySQLCluster(a.(*MySQLCluster), b.(*v1beta2.MySQLCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.MySQLClusterSpec)(nil), (*MySQLClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MySQLClusterSpec_To__MySQLClusterSpec(a.(*v1beta2.MySQLClusterSpec), b.(*MySQLClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.MySQLCluster)(nil), (*MySQLCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_MySQLCluster_To__MySQLCluster(a.(*v1beta2.MySQLCluster), b.(*MySQLCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1beta2.PodTemplateSpec)(nil), (*PodTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PodTemplateSpec_To__PodTemplateSpec(a.(*v1beta2.PodTemplateSpec), b.(*PodTemplateSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert__AffinityApplyConfiguration_To_v1beta2_AffinityApplyConfiguration(in *AffinityApplyConfiguration, out *v1beta2.AffinityApplyConfiguration, s conversion.Scope) error {
	out.NodeAffinity = (*v1.NodeAffinityApplyConfiguration)(unsafe.Pointer(in.NodeAffinity))
	out.PodAffinity = (*v1.PodAffinityApplyConfiguration)(unsafe.Pointer(in.PodAffinity))
	out.PodAntiAffinity = (*v1.PodAntiAffinityApplyConfiguration)(unsafe.Pointer(in.PodAntiAffinity))
	return nil
}

// Convert__AffinityApplyConfiguration_To_v1beta2_AffinityApplyConfiguration is an autogenerated conversion function.
func Convert__AffinityApplyConfiguration_To_v1beta2_AffinityApplyConfiguration(in *AffinityApplyConfiguration, out *v1beta2.AffinityApplyConfiguration, s conversion.Scope) error {
	return autoConvert__AffinityApplyConfiguration_To_v1beta2_AffinityApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_AffinityApplyConfiguration_To__AffinityApplyConfiguration(in *v1beta2.AffinityApplyConfiguration, out *AffinityApplyConfiguration, s conversion.Scope) error {
	out.NodeAffinity = (*v1.NodeAffinityApplyConfiguration)(unsafe.Pointer(in.NodeAffinity))
	out.PodAffinity = (*v1.PodAffinityApplyConfiguration)(unsafe.Pointer(in.PodAffinity))
	out.PodAntiAffinity = (*v1.PodAntiAffinityApplyConfiguration)(unsafe.Pointer(in.PodAntiAffinity))
	return nil
}

// Convert_v1beta2_AffinityApplyConfiguration_To__AffinityApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_AffinityApplyConfiguration_To__AffinityApplyConfiguration(in *v1beta2.AffinityApplyConfiguration, out *AffinityApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_AffinityApplyConfiguration_To__AffinityApplyConfiguration(in, out, s)
}

func autoConvert__BackupPolicy_To_v1beta2_BackupPolicy(in *BackupPolicy, out *v1beta2.BackupPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert__BackupPolicySpec_To_v1beta2_BackupPolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert__BackupPolicy_To_v1beta2_BackupPolicy is an autogenerated conversion function.
func Convert__BackupPolicy_To_v1beta2_BackupPolicy(in *BackupPolicy, out *v1beta2.BackupPolicy, s conversion.Scope) error {
	return autoConvert__BackupPolicy_To_v1beta2_BackupPolicy(in, out, s)
}

func autoConvert_v1beta2_BackupPolicy_To__BackupPolicy(in *v1beta2.BackupPolicy, out *BackupPolicy, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_BackupPolicySpec_To__BackupPolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_BackupPolicy_To__BackupPolicy is an autogenerated conversion function.
func Convert_v1beta2_BackupPolicy_To__BackupPolicy(in *v1beta2.BackupPolicy, out *BackupPolicy, s conversion.Scope) error {
	return autoConvert_v1beta2_BackupPolicy_To__BackupPolicy(in, out, s)
}

func autoConvert__BackupPolicyList_To_v1beta2_BackupPolicyList(in *BackupPolicyList, out *v1beta2.BackupPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta2.BackupPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert__BackupPolicyList_To_v1beta2_BackupPolicyList is an autogenerated conversion function.
func Convert__BackupPolicyList_To_v1beta2_BackupPolicyList(in *BackupPolicyList, out *v1beta2.BackupPolicyList, s conversion.Scope) error {
	return autoConvert__BackupPolicyList_To_v1beta2_BackupPolicyList(in, out, s)
}

func autoConvert_v1beta2_BackupPolicyList_To__BackupPolicyList(in *v1beta2.BackupPolicyList, out *BackupPolicyList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BackupPolicy)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta2_BackupPolicyList_To__BackupPolicyList is an autogenerated conversion function.
func Convert_v1beta2_BackupPolicyList_To__BackupPolicyList(in *v1beta2.BackupPolicyList, out *BackupPolicyList, s conversion.Scope) error {
	return autoConvert_v1beta2_BackupPolicyList_To__BackupPolicyList(in, out, s)
}

func autoConvert__BackupPolicySpec_To_v1beta2_BackupPolicySpec(in *BackupPolicySpec, out *v1beta2.BackupPolicySpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	if err := Convert__JobConfig_To_v1beta2_JobConfig(&in.JobConfig, &out.JobConfig, s); err != nil {
		return err
	}
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.ConcurrencyPolicy = batchv1.ConcurrencyPolicy(in.ConcurrencyPolicy)
	out.ActiveDeadlineSeconds = (*int64)(unsafe.Pointer(in.ActiveDeadlineSeconds))
	out.BackoffLimit = (*int32)(unsafe.Pointer(in.BackoffLimit))
	out.SuccessfulJobsHistoryLimit = (*int32)(unsafe.Pointer(in.SuccessfulJobsHistoryLimit))
	out.FailedJobsHistoryLimit = (*int32)(unsafe.Pointer(in.FailedJobsHistoryLimit))
	return nil
}

// Convert__BackupPolicySpec_To_v1beta2_BackupPolicySpec is an autogenerated conversion function.
func Convert__BackupPolicySpec_To_v1beta2_BackupPolicySpec(in *BackupPolicySpec, out *v1beta2.BackupPolicySpec, s conversion.Scope) error {
	return autoConvert__BackupPolicySpec_To_v1beta2_BackupPolicySpec(in, out, s)
}

func autoConvert_v1beta2_BackupPolicySpec_To__BackupPolicySpec(in *v1beta2.BackupPolicySpec, out *BackupPolicySpec, s conversion.Scope) error {
	out.Schedule = in.Schedule
	if err := Convert_v1beta2_JobConfig_To__JobConfig(&in.JobConfig, &out.JobConfig, s); err != nil {
		return err
	}
	out.StartingDeadlineSeconds = (*int64)(unsafe.Pointer(in.StartingDeadlineSeconds))
	out.ConcurrencyPolicy = batchv1.ConcurrencyPolicy(in.ConcurrencyPolicy)
	out.ActiveDeadlineSeconds = (*int64)(unsafe.Pointer(in.ActiveDeadlineSeconds))
	out.BackoffLimit = (*int32)(unsafe.Pointer(in.BackoffLimit))
	out.SuccessfulJobsHistoryLimit = (*int32)(unsafe.Pointer(in.SuccessfulJobsHistoryLimit))
	out.FailedJobsHistoryLimit = (*int32)(unsafe.Pointer(in.FailedJobsHistoryLimit))
	return nil
}

// Convert_v1beta2_BackupPolicySpec_To__BackupPolicySpec is an autogenerated conversion function.
func Convert_v1beta2_BackupPolicySpec_To__BackupPolicySpec(in *v1beta2.BackupPolicySpec, out *BackupPolicySpec, s conversion.Scope) error {
	return autoConvert_v1beta2_BackupPolicySpec_To__BackupPolicySpec(in, out, s)
}

func autoConvert__BackupStatus_To_v1beta2_BackupStatus(in *BackupStatus, out *v1beta2.BackupStatus, s conversion.Scope) error {
	out.Time = in.Time
	out.Elapsed = in.Elapsed
	out.SourceIndex = in.SourceIndex
	out.SourceUUID = in.SourceUUID
	out.BinlogFilename = in.BinlogFilename
	out.GTIDSet = in.GTIDSet
	out.DumpSize = in.DumpSize
	out.BinlogSize = in.BinlogSize
	out.WorkDirUsage = in.WorkDirUsage
	out.Warnings = *(*[]string)(unsafe.Pointer(&in.Warnings))
	return nil
}

// Convert__BackupStatus_To_v1beta2_BackupStatus is an autogenerated conversion function.
func Convert__BackupStatus_To_v1beta2_BackupStatus(in *BackupStatus, out *v1beta2.BackupStatus, s conversion.Scope) error {
	return autoConvert__BackupStatus_To_v1beta2_BackupStatus(in, out, s)
}

func autoConvert_v1beta2_BackupStatus_To__BackupStatus(in *v1beta2.BackupStatus, out *BackupStatus, s conversion.Scope) error {
	out.Time = in.Time
	out.Elapsed = in.Elapsed
	out.SourceIndex = in.SourceIndex
	out.SourceUUID = in.SourceUUID
	out.BinlogFilename = in.BinlogFilename
	out.GTIDSet = in.GTIDSet
	out.DumpSize = in.DumpSize
	out.BinlogSize = in.BinlogSize
	out.WorkDirUsage = in.WorkDirUsage
	out.Warnings = *(*[]string)(unsafe.Pointer(&in.Warnings))
	return nil
}

// Convert_v1beta2_BackupStatus_To__BackupStatus is an autogenerated conversion function.
func Convert_v1beta2_BackupStatus_To__BackupStatus(in *v1beta2.BackupStatus, out *BackupStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_BackupStatus_To__BackupStatus(in, out, s)
}

func autoConvert__BucketConfig_To_v1beta2_BucketConfig(in *BucketConfig, out *v1beta2.BucketConfig, s conversion.Scope) error {
	out.BucketName = in.BucketName
	out.Region = in.Region
	out.EndpointURL = in.EndpointURL
	out.UsePathStyle = in.UsePathStyle
	out.BackendType = in.BackendType
	return nil
}

// Convert__BucketConfig_To_v1beta2_BucketConfig is an autogenerated conversion function.
func Convert__BucketConfig_To_v1beta2_BucketConfig(in *BucketConfig, out *v1beta2.BucketConfig, s conversion.Scope) error {
	return autoConvert__BucketConfig_To_v1beta2_BucketConfig(in, out, s)
}

func autoConvert_v1beta2_BucketConfig_To__BucketConfig(in *v1beta2.BucketConfig, out *BucketConfig, s conversion.Scope) error {
	out.BucketName = in.BucketName
	out.Region = in.Region
	out.EndpointURL = in.EndpointURL
	out.UsePathStyle = in.UsePathStyle
	out.BackendType = in.BackendType
	return nil
}

// Convert_v1beta2_BucketConfig_To__BucketConfig is an autogenerated conversion function.
func Convert_v1beta2_BucketConfig_To__BucketConfig(in *v1beta2.BucketConfig, out *BucketConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_BucketConfig_To__BucketConfig(in, out, s)
}

func autoConvert__EnvFromSourceApplyConfiguration_To_v1beta2_EnvFromSourceApplyConfiguration(in *EnvFromSourceApplyConfiguration, out *v1beta2.EnvFromSourceApplyConfiguration, s conversion.Scope) error {
	out.Prefix = (*string)(unsafe.Pointer(in.Prefix))
	out.ConfigMapRef = (*v1.ConfigMapEnvSourceApplyConfiguration)(unsafe.Pointer(in.ConfigMapRef))
	out.SecretRef = (*v1.SecretEnvSourceApplyConfiguration)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert__EnvFromSourceApplyConfiguration_To_v1beta2_EnvFromSourceApplyConfiguration is an autogenerated conversion function.
func Convert__EnvFromSourceApplyConfiguration_To_v1beta2_EnvFromSourceApplyConfiguration(in *EnvFromSourceApplyConfiguration, out *v1beta2.EnvFromSourceApplyConfiguration, s conversion.Scope) error {
	return autoConvert__EnvFromSourceApplyConfiguration_To_v1beta2_EnvFromSourceApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_EnvFromSourceApplyConfiguration_To__EnvFromSourceApplyConfiguration(in *v1beta2.EnvFromSourceApplyConfiguration, out *EnvFromSourceApplyConfiguration, s conversion.Scope) error {
	out.Prefix = (*string)(unsafe.Pointer(in.Prefix))
	out.ConfigMapRef = (*v1.ConfigMapEnvSourceApplyConfiguration)(unsafe.Pointer(in.ConfigMapRef))
	out.SecretRef = (*v1.SecretEnvSourceApplyConfiguration)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert_v1beta2_EnvFromSourceApplyConfiguration_To__EnvFromSourceApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_EnvFromSourceApplyConfiguration_To__EnvFromSourceApplyConfiguration(in *v1beta2.EnvFromSourceApplyConfiguration, out *EnvFromSourceApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_EnvFromSourceApplyConfiguration_To__EnvFromSourceApplyConfiguration(in, out, s)
}

func autoConvert__EnvVarApplyConfiguration_To_v1beta2_EnvVarApplyConfiguration(in *EnvVarApplyConfiguration, out *v1beta2.EnvVarApplyConfiguration, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.Value = (*string)(unsafe.Pointer(in.Value))
	out.ValueFrom = (*v1.EnvVarSourceApplyConfiguration)(unsafe.Pointer(in.ValueFrom))
	return nil
}

// Convert__EnvVarApplyConfiguration_To_v1beta2_EnvVarApplyConfiguration is an autogenerated conversion function.
func Convert__EnvVarApplyConfiguration_To_v1beta2_EnvVarApplyConfiguration(in *EnvVarApplyConfiguration, out *v1beta2.EnvVarApplyConfiguration, s conversion.Scope) error {
	return autoConvert__EnvVarApplyConfiguration_To_v1beta2_EnvVarApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_EnvVarApplyConfiguration_To__EnvVarApplyConfiguration(in *v1beta2.EnvVarApplyConfiguration, out *EnvVarApplyConfiguration, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.Value = (*string)(unsafe.Pointer(in.Value))
	out.ValueFrom = (*v1.EnvVarSourceApplyConfiguration)(unsafe.Pointer(in.ValueFrom))
	return nil
}

// Convert_v1beta2_EnvVarApplyConfiguration_To__EnvVarApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_EnvVarApplyConfiguration_To__EnvVarApplyConfiguration(in *v1beta2.EnvVarApplyConfiguration, out *EnvVarApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_EnvVarApplyConfiguration_To__EnvVarApplyConfiguration(in, out, s)
}

func autoConvert__JobConfig_To_v1beta2_JobConfig(in *JobConfig, out *v1beta2.JobConfig, s conversion.Scope) error {
	out.ServiceAccountName = in.ServiceAccountName
	if err := Convert__BucketConfig_To_v1beta2_BucketConfig(&in.BucketConfig, &out.BucketConfig, s); err != nil {
		return err
	}
	if err := Convert__VolumeSourceApplyConfiguration_To_v1beta2_VolumeSourceApplyConfiguration(&in.WorkVolume, &out.WorkVolume, s); err != nil {
		return err
	}
	out.Threads = in.Threads
	out.Memory = (*resource.Quantity)(unsafe.Pointer(in.Memory))
	out.MaxMemory = (*resource.Quantity)(unsafe.Pointer(in.MaxMemory))
	out.EnvFrom = *(*[]v1beta2.EnvFromSourceApplyConfiguration)(unsafe.Pointer(&in.EnvFrom))
	out.Env = *(*[]v1beta2.EnvVarApplyConfiguration)(unsafe.Pointer(&in.Env))
	out.Affinity = (*v1beta2.AffinityApplyConfiguration)(unsafe.Pointer(in.Affinity))
	out.Volumes = *(*[]v1beta2.VolumeApplyConfiguration)(unsafe.Pointer(&in.Volumes))
	out.VolumeMounts = *(*[]v1beta2.VolumeMountApplyConfiguration)(unsafe.Pointer(&in.VolumeMounts))
	return nil
}

// Convert__JobConfig_To_v1beta2_JobConfig is an autogenerated conversion function.
func Convert__JobConfig_To_v1beta2_JobConfig(in *JobConfig, out *v1beta2.JobConfig, s conversion.Scope) error {
	return autoConvert__JobConfig_To_v1beta2_JobConfig(in, out, s)
}

func autoConvert_v1beta2_JobConfig_To__JobConfig(in *v1beta2.JobConfig, out *JobConfig, s conversion.Scope) error {
	out.ServiceAccountName = in.ServiceAccountName
	if err := Convert_v1beta2_BucketConfig_To__BucketConfig(&in.BucketConfig, &out.BucketConfig, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_VolumeSourceApplyConfiguration_To__VolumeSourceApplyConfiguration(&in.WorkVolume, &out.WorkVolume, s); err != nil {
		return err
	}
	out.Threads = in.Threads
	out.Memory = (*resource.Quantity)(unsafe.Pointer(in.Memory))
	out.MaxMemory = (*resource.Quantity)(unsafe.Pointer(in.MaxMemory))
	out.EnvFrom = *(*[]EnvFromSourceApplyConfiguration)(unsafe.Pointer(&in.EnvFrom))
	out.Env = *(*[]EnvVarApplyConfiguration)(unsafe.Pointer(&in.Env))
	out.Affinity = (*AffinityApplyConfiguration)(unsafe.Pointer(in.Affinity))
	out.Volumes = *(*[]VolumeApplyConfiguration)(unsafe.Pointer(&in.Volumes))
	out.VolumeMounts = *(*[]VolumeMountApplyConfiguration)(unsafe.Pointer(&in.VolumeMounts))
	return nil
}

// Convert_v1beta2_JobConfig_To__JobConfig is an autogenerated conversion function.
func Convert_v1beta2_JobConfig_To__JobConfig(in *v1beta2.JobConfig, out *JobConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_JobConfig_To__JobConfig(in, out, s)
}

func autoConvert__MySQLCluster_To_v1beta2_MySQLCluster(in *MySQLCluster, out *v1beta2.MySQLCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert__MySQLClusterSpec_To_v1beta2_MySQLClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert__MySQLClusterStatus_To_v1beta2_MySQLClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta2_MySQLCluster_To__MySQLCluster(in *v1beta2.MySQLCluster, out *MySQLCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_MySQLClusterSpec_To__MySQLClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_MySQLClusterStatus_To__MySQLClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func autoConvert__MySQLClusterCondition_To_v1beta2_MySQLClusterCondition(in *MySQLClusterCondition, out *v1beta2.MySQLClusterCondition, s conversion.Scope) error {
	out.Type = v1beta2.MySQLClusterConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert__MySQLClusterCondition_To_v1beta2_MySQLClusterCondition is an autogenerated conversion function.
func Convert__MySQLClusterCondition_To_v1beta2_MySQLClusterCondition(in *MySQLClusterCondition, out *v1beta2.MySQLClusterCondition, s conversion.Scope) error {
	return autoConvert__MySQLClusterCondition_To_v1beta2_MySQLClusterCondition(in, out, s)
}

func autoConvert_v1beta2_MySQLClusterCondition_To__MySQLClusterCondition(in *v1beta2.MySQLClusterCondition, out *MySQLClusterCondition, s conversion.Scope) error {
	out.Type = MySQLClusterConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastTransitionTime = in.LastTransitionTime
	return nil
}

// Convert_v1beta2_MySQLClusterCondition_To__MySQLClusterCondition is an autogenerated conversion function.
func Convert_v1beta2_MySQLClusterCondition_To__MySQLClusterCondition(in *v1beta2.MySQLClusterCondition, out *MySQLClusterCondition, s conversion.Scope) error {
	return autoConvert_v1beta2_MySQLClusterCondition_To__MySQLClusterCondition(in, out, s)
}

func autoConvert__MySQLClusterList_To_v1beta2_MySQLClusterList(in *MySQLClusterList, out *v1beta2.MySQLClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1beta2.MySQLCluster, len(*in))
		for i := range *in {
			if err := Convert__MySQLCluster_To_v1beta2_MySQLCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert__MySQLClusterList_To_v1beta2_MySQLClusterList is an autogenerated conversion function.
func Convert__MySQLClusterList_To_v1beta2_MySQLClusterList(in *MySQLClusterList, out *v1beta2.MySQLClusterList, s conversion.Scope) error {
	return autoConvert__MySQLClusterList_To_v1beta2_MySQLClusterList(in, out, s)
}

func autoConvert_v1beta2_MySQLClusterList_To__MySQLClusterList(in *v1beta2.MySQLClusterList, out *MySQLClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MySQLCluster, len(*in))
		for i := range *in {
			if err := Convert_v1beta2_MySQLCluster_To__MySQLCluster(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta2_MySQLClusterList_To__MySQLClusterList is an autogenerated conversion function.
func Convert_v1beta2_MySQLClusterList_To__MySQLClusterList(in *v1beta2.MySQLClusterList, out *MySQLClusterList, s conversion.Scope) error {
	return autoConvert_v1beta2_MySQLClusterList_To__MySQLClusterList(in, out, s)
}

func autoConvert__MySQLClusterSpec_To_v1beta2_MySQLClusterSpec(in *MySQLClusterSpec, out *v1beta2.MySQLClusterSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	if err := Convert__PodTemplateSpec_To_v1beta2_PodTemplateSpec(&in.PodTemplate, &out.PodTemplate, s); err != nil {
		return err
	}
	out.VolumeClaimTemplates = *(*[]v1beta2.PersistentVolumeClaim)(unsafe.Pointer(&in.VolumeClaimTemplates))
	// WARNING: in.ServiceTemplate requires manual conversion: does not exist in peer-type
	out.MySQLConfigMapName = (*string)(unsafe.Pointer(in.MySQLConfigMapName))
	out.ReplicationSourceSecretName = (*string)(unsafe.Pointer(in.ReplicationSourceSecretName))
	out.Collectors = *(*[]string)(unsafe.Pointer(&in.Collectors))
	out.ServerIDBase = in.ServerIDBase
	out.MaxDelaySeconds = (*int)(unsafe.Pointer(in.MaxDelaySeconds))
	out.StartupWaitSeconds = in.StartupWaitSeconds
	out.LogRotationSchedule = in.LogRotationSchedule
	out.BackupPolicyName = (*string)(unsafe.Pointer(in.BackupPolicyName))
	out.Restore = (*v1beta2.RestoreSpec)(unsafe.Pointer(in.Restore))
	out.DisableSlowQueryLogContainer = in.DisableSlowQueryLogContainer
	return nil
}

func autoConvert_v1beta2_MySQLClusterSpec_To__MySQLClusterSpec(in *v1beta2.MySQLClusterSpec, out *MySQLClusterSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	if err := Convert_v1beta2_PodTemplateSpec_To__PodTemplateSpec(&in.PodTemplate, &out.PodTemplate, s); err != nil {
		return err
	}
	out.VolumeClaimTemplates = *(*[]PersistentVolumeClaim)(unsafe.Pointer(&in.VolumeClaimTemplates))
	// WARNING: in.PrimaryServiceTemplate requires manual conversion: does not exist in peer-type
	// WARNING: in.ReplicaServiceTemplate requires manual conversion: does not exist in peer-type
	out.MySQLConfigMapName = (*string)(unsafe.Pointer(in.MySQLConfigMapName))
	out.ReplicationSourceSecretName = (*string)(unsafe.Pointer(in.ReplicationSourceSecretName))
	out.Collectors = *(*[]string)(unsafe.Pointer(&in.Collectors))
	out.ServerIDBase = in.ServerIDBase
	out.MaxDelaySeconds = (*int)(unsafe.Pointer(in.MaxDelaySeconds))
	out.StartupWaitSeconds = in.StartupWaitSeconds
	out.LogRotationSchedule = in.LogRotationSchedule
	out.BackupPolicyName = (*string)(unsafe.Pointer(in.BackupPolicyName))
	out.Restore = (*RestoreSpec)(unsafe.Pointer(in.Restore))
	out.DisableSlowQueryLogContainer = in.DisableSlowQueryLogContainer
	return nil
}

func autoConvert__MySQLClusterStatus_To_v1beta2_MySQLClusterStatus(in *MySQLClusterStatus, out *v1beta2.MySQLClusterStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1beta2.MySQLClusterCondition)(unsafe.Pointer(&in.Conditions))
	out.CurrentPrimaryIndex = in.CurrentPrimaryIndex
	out.SyncedReplicas = in.SyncedReplicas
	out.ErrantReplicas = in.ErrantReplicas
	out.ErrantReplicaList = *(*[]int)(unsafe.Pointer(&in.ErrantReplicaList))
	if err := Convert__BackupStatus_To_v1beta2_BackupStatus(&in.Backup, &out.Backup, s); err != nil {
		return err
	}
	out.RestoredTime = (*metav1.Time)(unsafe.Pointer(in.RestoredTime))
	out.Cloned = in.Cloned
	if err := Convert__ReconcileInfo_To_v1beta2_ReconcileInfo(&in.ReconcileInfo, &out.ReconcileInfo, s); err != nil {
		return err
	}
	return nil
}

// Convert__MySQLClusterStatus_To_v1beta2_MySQLClusterStatus is an autogenerated conversion function.
func Convert__MySQLClusterStatus_To_v1beta2_MySQLClusterStatus(in *MySQLClusterStatus, out *v1beta2.MySQLClusterStatus, s conversion.Scope) error {
	return autoConvert__MySQLClusterStatus_To_v1beta2_MySQLClusterStatus(in, out, s)
}

func autoConvert_v1beta2_MySQLClusterStatus_To__MySQLClusterStatus(in *v1beta2.MySQLClusterStatus, out *MySQLClusterStatus, s conversion.Scope) error {
	out.Conditions = *(*[]MySQLClusterCondition)(unsafe.Pointer(&in.Conditions))
	out.CurrentPrimaryIndex = in.CurrentPrimaryIndex
	out.SyncedReplicas = in.SyncedReplicas
	out.ErrantReplicas = in.ErrantReplicas
	out.ErrantReplicaList = *(*[]int)(unsafe.Pointer(&in.ErrantReplicaList))
	if err := Convert_v1beta2_BackupStatus_To__BackupStatus(&in.Backup, &out.Backup, s); err != nil {
		return err
	}
	out.RestoredTime = (*metav1.Time)(unsafe.Pointer(in.RestoredTime))
	out.Cloned = in.Cloned
	if err := Convert_v1beta2_ReconcileInfo_To__ReconcileInfo(&in.ReconcileInfo, &out.ReconcileInfo, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_MySQLClusterStatus_To__MySQLClusterStatus is an autogenerated conversion function.
func Convert_v1beta2_MySQLClusterStatus_To__MySQLClusterStatus(in *v1beta2.MySQLClusterStatus, out *MySQLClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_MySQLClusterStatus_To__MySQLClusterStatus(in, out, s)
}

func autoConvert__ObjectMeta_To_v1beta2_ObjectMeta(in *ObjectMeta, out *v1beta2.ObjectMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert__ObjectMeta_To_v1beta2_ObjectMeta is an autogenerated conversion function.
func Convert__ObjectMeta_To_v1beta2_ObjectMeta(in *ObjectMeta, out *v1beta2.ObjectMeta, s conversion.Scope) error {
	return autoConvert__ObjectMeta_To_v1beta2_ObjectMeta(in, out, s)
}

func autoConvert_v1beta2_ObjectMeta_To__ObjectMeta(in *v1beta2.ObjectMeta, out *ObjectMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1beta2_ObjectMeta_To__ObjectMeta is an autogenerated conversion function.
func Convert_v1beta2_ObjectMeta_To__ObjectMeta(in *v1beta2.ObjectMeta, out *ObjectMeta, s conversion.Scope) error {
	return autoConvert_v1beta2_ObjectMeta_To__ObjectMeta(in, out, s)
}

func autoConvert__PersistentVolumeClaim_To_v1beta2_PersistentVolumeClaim(in *PersistentVolumeClaim, out *v1beta2.PersistentVolumeClaim, s conversion.Scope) error {
	if err := Convert__ObjectMeta_To_v1beta2_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert__PersistentVolumeClaimSpecApplyConfiguration_To_v1beta2_PersistentVolumeClaimSpecApplyConfiguration(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert__PersistentVolumeClaim_To_v1beta2_PersistentVolumeClaim is an autogenerated conversion function.
func Convert__PersistentVolumeClaim_To_v1beta2_PersistentVolumeClaim(in *PersistentVolumeClaim, out *v1beta2.PersistentVolumeClaim, s conversion.Scope) error {
	return autoConvert__PersistentVolumeClaim_To_v1beta2_PersistentVolumeClaim(in, out, s)
}

func autoConvert_v1beta2_PersistentVolumeClaim_To__PersistentVolumeClaim(in *v1beta2.PersistentVolumeClaim, out *PersistentVolumeClaim, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To__ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_PersistentVolumeClaimSpecApplyConfiguration_To__PersistentVolumeClaimSpecApplyConfiguration(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_PersistentVolumeClaim_To__PersistentVolumeClaim is an autogenerated conversion function.
func Convert_v1beta2_PersistentVolumeClaim_To__PersistentVolumeClaim(in *v1beta2.PersistentVolumeClaim, out *PersistentVolumeClaim, s conversion.Scope) error {
	return autoConvert_v1beta2_PersistentVolumeClaim_To__PersistentVolumeClaim(in, out, s)
}

func autoConvert__PersistentVolumeClaimSpecApplyConfiguration_To_v1beta2_PersistentVolumeClaimSpecApplyConfiguration(in *PersistentVolumeClaimSpecApplyConfiguration, out *v1beta2.PersistentVolumeClaimSpecApplyConfiguration, s conversion.Scope) error {
	out.AccessModes = *(*[]corev1.PersistentVolumeAccessMode)(unsafe.Pointer(&in.AccessModes))
	out.Selector = (*applyconfigurationsmetav1.LabelSelectorApplyConfiguration)(unsafe.Pointer(in.Selector))
	out.Resources = (*v1.ResourceRequirementsApplyConfiguration)(unsafe.Pointer(in.Resources))
	out.VolumeName = (*string)(unsafe.Pointer(in.VolumeName))
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	out.VolumeMode = (*corev1.PersistentVolumeMode)(unsafe.Pointer(in.VolumeMode))
	out.DataSource = (*v1.TypedLocalObjectReferenceApplyConfiguration)(unsafe.Pointer(in.DataSource))
	out.DataSourceRef = (*v1.TypedObjectReferenceApplyConfiguration)(unsafe.Pointer(in.DataSourceRef))
	return nil
}

// Convert__PersistentVolumeClaimSpecApplyConfiguration_To_v1beta2_PersistentVolumeClaimSpecApplyConfiguration is an autogenerated conversion function.
func Convert__PersistentVolumeClaimSpecApplyConfiguration_To_v1beta2_PersistentVolumeClaimSpecApplyConfiguration(in *PersistentVolumeClaimSpecApplyConfiguration, out *v1beta2.PersistentVolumeClaimSpecApplyConfiguration, s conversion.Scope) error {
	return autoConvert__PersistentVolumeClaimSpecApplyConfiguration_To_v1beta2_PersistentVolumeClaimSpecApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_PersistentVolumeClaimSpecApplyConfiguration_To__PersistentVolumeClaimSpecApplyConfiguration(in *v1beta2.PersistentVolumeClaimSpecApplyConfiguration, out *PersistentVolumeClaimSpecApplyConfiguration, s conversion.Scope) error {
	out.AccessModes = *(*[]corev1.PersistentVolumeAccessMode)(unsafe.Pointer(&in.AccessModes))
	out.Selector = (*applyconfigurationsmetav1.LabelSelectorApplyConfiguration)(unsafe.Pointer(in.Selector))
	out.Resources = (*v1.ResourceRequirementsApplyConfiguration)(unsafe.Pointer(in.Resources))
	out.VolumeName = (*string)(unsafe.Pointer(in.VolumeName))
	out.StorageClassName = (*string)(unsafe.Pointer(in.StorageClassName))
	out.VolumeMode = (*corev1.PersistentVolumeMode)(unsafe.Pointer(in.VolumeMode))
	out.DataSource = (*v1.TypedLocalObjectReferenceApplyConfiguration)(unsafe.Pointer(in.DataSource))
	out.DataSourceRef = (*v1.TypedObjectReferenceApplyConfiguration)(unsafe.Pointer(in.DataSourceRef))
	return nil
}

// Convert_v1beta2_PersistentVolumeClaimSpecApplyConfiguration_To__PersistentVolumeClaimSpecApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_PersistentVolumeClaimSpecApplyConfiguration_To__PersistentVolumeClaimSpecApplyConfiguration(in *v1beta2.PersistentVolumeClaimSpecApplyConfiguration, out *PersistentVolumeClaimSpecApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_PersistentVolumeClaimSpecApplyConfiguration_To__PersistentVolumeClaimSpecApplyConfiguration(in, out, s)
}

func autoConvert__PodSpecApplyConfiguration_To_v1beta2_PodSpecApplyConfiguration(in *PodSpecApplyConfiguration, out *v1beta2.PodSpecApplyConfiguration, s conversion.Scope) error {
	out.Volumes = *(*[]v1.VolumeApplyConfiguration)(unsafe.Pointer(&in.Volumes))
	out.InitContainers = *(*[]v1.ContainerApplyConfiguration)(unsafe.Pointer(&in.InitContainers))
	out.Containers = *(*[]v1.ContainerApplyConfiguration)(unsafe.Pointer(&in.Containers))
	out.EphemeralContainers = *(*[]v1.EphemeralContainerApplyConfiguration)(unsafe.Pointer(&in.EphemeralContainers))
	out.RestartPolicy = (*corev1.RestartPolicy)(unsafe.Pointer(in.RestartPolicy))
	out.TerminationGracePeriodSeconds = (*int64)(unsafe.Pointer(in.TerminationGracePeriodSeconds))
	out.ActiveDeadlineSeconds = (*int64)(unsafe.Pointer(in.ActiveDeadlineSeconds))
	out.DNSPolicy = (*corev1.DNSPolicy)(unsafe.Pointer(in.DNSPolicy))
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.ServiceAccountName = (*string)(unsafe.Pointer(in.ServiceAccountName))
	out.DeprecatedServiceAccount = (*string)(unsafe.Pointer(in.DeprecatedServiceAccount))
	out.AutomountServiceAccountToken = (*bool)(unsafe.Pointer(in.AutomountServiceAccountToken))
	out.NodeName = (*string)(unsafe.Pointer(in.NodeName))
	out.HostNetwork = (*bool)(unsafe.Pointer(in.HostNetwork))
	out.HostPID = (*bool)(unsafe.Pointer(in.HostPID))
	out.HostIPC = (*bool)(unsafe.Pointer(in.HostIPC))
	out.ShareProcessNamespace = (*bool)(unsafe.Pointer(in.ShareProcessNamespace))
	out.SecurityContext = (*v1.PodSecurityContextApplyConfiguration)(unsafe.Pointer(in.SecurityContext))
	out.ImagePullSecrets = *(*[]v1.LocalObjectReferenceApplyConfiguration)(unsafe.Pointer(&in.ImagePullSecrets))
	out.Hostname = (*string)(unsafe.Pointer(in.Hostname))
	out.Subdomain = (*string)(unsafe.Pointer(in.Subdomain))
	out.Affinity = (*v1.AffinityApplyConfiguration)(unsafe.Pointer(in.Affinity))
	out.SchedulerName = (*string)(unsafe.Pointer(in.SchedulerName))
	out.Tolerations = *(*[]v1.TolerationApplyConfiguration)(unsafe.Pointer(&in.Tolerations))
	out.HostAliases = *(*[]v1.HostAliasApplyConfiguration)(unsafe.Pointer(&in.HostAliases))
	out.PriorityClassName = (*string)(unsafe.Pointer(in.PriorityClassName))
	out.Priority = (*int32)(unsafe.Pointer(in.Priority))
	out.DNSConfig = (*v1.PodDNSConfigApplyConfiguration)(unsafe.Pointer(in.DNSConfig))
	out.ReadinessGates = *(*[]v1.PodReadinessGateApplyConfiguration)(unsafe.Pointer(&in.ReadinessGates))
	out.RuntimeClassName = (*string)(unsafe.Pointer(in.RuntimeClassName))
	out.EnableServiceLinks = (*bool)(unsafe.Pointer(in.EnableServiceLinks))
	out.PreemptionPolicy = (*corev1.PreemptionPolicy)(unsafe.Pointer(in.PreemptionPolicy))
	out.Overhead = (*corev1.ResourceList)(unsafe.Pointer(in.Overhead))
	out.TopologySpreadConstraints = *(*[]v1.TopologySpreadConstraintApplyConfiguration)(unsafe.Pointer(&in.TopologySpreadConstraints))
	out.SetHostnameAsFQDN = (*bool)(unsafe.Pointer(in.SetHostnameAsFQDN))
	out.OS = (*v1.PodOSApplyConfiguration)(unsafe.Pointer(in.OS))
	out.HostUsers = (*bool)(unsafe.Pointer(in.HostUsers))
	out.SchedulingGates = *(*[]v1.PodSchedulingGateApplyConfiguration)(unsafe.Pointer(&in.SchedulingGates))
	out.ResourceClaims = *(*[]v1.PodResourceClaimApplyConfiguration)(unsafe.Pointer(&in.ResourceClaims))
	return nil
}

// Convert__PodSpecApplyConfiguration_To_v1beta2_PodSpecApplyConfiguration is an autogenerated conversion function.
func Convert__PodSpecApplyConfiguration_To_v1beta2_PodSpecApplyConfiguration(in *PodSpecApplyConfiguration, out *v1beta2.PodSpecApplyConfiguration, s conversion.Scope) error {
	return autoConvert__PodSpecApplyConfiguration_To_v1beta2_PodSpecApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_PodSpecApplyConfiguration_To__PodSpecApplyConfiguration(in *v1beta2.PodSpecApplyConfiguration, out *PodSpecApplyConfiguration, s conversion.Scope) error {
	out.Volumes = *(*[]v1.VolumeApplyConfiguration)(unsafe.Pointer(&in.Volumes))
	out.InitContainers = *(*[]v1.ContainerApplyConfiguration)(unsafe.Pointer(&in.InitContainers))
	out.Containers = *(*[]v1.ContainerApplyConfiguration)(unsafe.Pointer(&in.Containers))
	out.EphemeralContainers = *(*[]v1.EphemeralContainerApplyConfiguration)(unsafe.Pointer(&in.EphemeralContainers))
	out.RestartPolicy = (*corev1.RestartPolicy)(unsafe.Pointer(in.RestartPolicy))
	out.TerminationGracePeriodSeconds = (*int64)(unsafe.Pointer(in.TerminationGracePeriodSeconds))
	out.ActiveDeadlineSeconds = (*int64)(unsafe.Pointer(in.ActiveDeadlineSeconds))
	out.DNSPolicy = (*corev1.DNSPolicy)(unsafe.Pointer(in.DNSPolicy))
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.ServiceAccountName = (*string)(unsafe.Pointer(in.ServiceAccountName))
	out.DeprecatedServiceAccount = (*string)(unsafe.Pointer(in.DeprecatedServiceAccount))
	out.AutomountServiceAccountToken = (*bool)(unsafe.Pointer(in.AutomountServiceAccountToken))
	out.NodeName = (*string)(unsafe.Pointer(in.NodeName))
	out.HostNetwork = (*bool)(unsafe.Pointer(in.HostNetwork))
	out.HostPID = (*bool)(unsafe.Pointer(in.HostPID))
	out.HostIPC = (*bool)(unsafe.Pointer(in.HostIPC))
	out.ShareProcessNamespace = (*bool)(unsafe.Pointer(in.ShareProcessNamespace))
	out.SecurityContext = (*v1.PodSecurityContextApplyConfiguration)(unsafe.Pointer(in.SecurityContext))
	out.ImagePullSecrets = *(*[]v1.LocalObjectReferenceApplyConfiguration)(unsafe.Pointer(&in.ImagePullSecrets))
	out.Hostname = (*string)(unsafe.Pointer(in.Hostname))
	out.Subdomain = (*string)(unsafe.Pointer(in.Subdomain))
	out.Affinity = (*v1.AffinityApplyConfiguration)(unsafe.Pointer(in.Affinity))
	out.SchedulerName = (*string)(unsafe.Pointer(in.SchedulerName))
	out.Tolerations = *(*[]v1.TolerationApplyConfiguration)(unsafe.Pointer(&in.Tolerations))
	out.HostAliases = *(*[]v1.HostAliasApplyConfiguration)(unsafe.Pointer(&in.HostAliases))
	out.PriorityClassName = (*string)(unsafe.Pointer(in.PriorityClassName))
	out.Priority = (*int32)(unsafe.Pointer(in.Priority))
	out.DNSConfig = (*v1.PodDNSConfigApplyConfiguration)(unsafe.Pointer(in.DNSConfig))
	out.ReadinessGates = *(*[]v1.PodReadinessGateApplyConfiguration)(unsafe.Pointer(&in.ReadinessGates))
	out.RuntimeClassName = (*string)(unsafe.Pointer(in.RuntimeClassName))
	out.EnableServiceLinks = (*bool)(unsafe.Pointer(in.EnableServiceLinks))
	out.PreemptionPolicy = (*corev1.PreemptionPolicy)(unsafe.Pointer(in.PreemptionPolicy))
	out.Overhead = (*corev1.ResourceList)(unsafe.Pointer(in.Overhead))
	out.TopologySpreadConstraints = *(*[]v1.TopologySpreadConstraintApplyConfiguration)(unsafe.Pointer(&in.TopologySpreadConstraints))
	out.SetHostnameAsFQDN = (*bool)(unsafe.Pointer(in.SetHostnameAsFQDN))
	out.OS = (*v1.PodOSApplyConfiguration)(unsafe.Pointer(in.OS))
	out.HostUsers = (*bool)(unsafe.Pointer(in.HostUsers))
	out.SchedulingGates = *(*[]v1.PodSchedulingGateApplyConfiguration)(unsafe.Pointer(&in.SchedulingGates))
	out.ResourceClaims = *(*[]v1.PodResourceClaimApplyConfiguration)(unsafe.Pointer(&in.ResourceClaims))
	return nil
}

// Convert_v1beta2_PodSpecApplyConfiguration_To__PodSpecApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_PodSpecApplyConfiguration_To__PodSpecApplyConfiguration(in *v1beta2.PodSpecApplyConfiguration, out *PodSpecApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_PodSpecApplyConfiguration_To__PodSpecApplyConfiguration(in, out, s)
}

func autoConvert__PodTemplateSpec_To_v1beta2_PodTemplateSpec(in *PodTemplateSpec, out *v1beta2.PodTemplateSpec, s conversion.Scope) error {
	if err := Convert__ObjectMeta_To_v1beta2_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert__PodSpecApplyConfiguration_To_v1beta2_PodSpecApplyConfiguration(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert__PodTemplateSpec_To_v1beta2_PodTemplateSpec is an autogenerated conversion function.
func Convert__PodTemplateSpec_To_v1beta2_PodTemplateSpec(in *PodTemplateSpec, out *v1beta2.PodTemplateSpec, s conversion.Scope) error {
	return autoConvert__PodTemplateSpec_To_v1beta2_PodTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_PodTemplateSpec_To__PodTemplateSpec(in *v1beta2.PodTemplateSpec, out *PodTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To__ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_PodSpecApplyConfiguration_To__PodSpecApplyConfiguration(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	// WARNING: in.OverwriteContainers requires manual conversion: does not exist in peer-type
	return nil
}

func autoConvert__ReconcileInfo_To_v1beta2_ReconcileInfo(in *ReconcileInfo, out *v1beta2.ReconcileInfo, s conversion.Scope) error {
	out.Generation = in.Generation
	out.ReconcileVersion = in.ReconcileVersion
	return nil
}

// Convert__ReconcileInfo_To_v1beta2_ReconcileInfo is an autogenerated conversion function.
func Convert__ReconcileInfo_To_v1beta2_ReconcileInfo(in *ReconcileInfo, out *v1beta2.ReconcileInfo, s conversion.Scope) error {
	return autoConvert__ReconcileInfo_To_v1beta2_ReconcileInfo(in, out, s)
}

func autoConvert_v1beta2_ReconcileInfo_To__ReconcileInfo(in *v1beta2.ReconcileInfo, out *ReconcileInfo, s conversion.Scope) error {
	out.Generation = in.Generation
	out.ReconcileVersion = in.ReconcileVersion
	return nil
}

// Convert_v1beta2_ReconcileInfo_To__ReconcileInfo is an autogenerated conversion function.
func Convert_v1beta2_ReconcileInfo_To__ReconcileInfo(in *v1beta2.ReconcileInfo, out *ReconcileInfo, s conversion.Scope) error {
	return autoConvert_v1beta2_ReconcileInfo_To__ReconcileInfo(in, out, s)
}

func autoConvert__RestoreSpec_To_v1beta2_RestoreSpec(in *RestoreSpec, out *v1beta2.RestoreSpec, s conversion.Scope) error {
	out.SourceName = in.SourceName
	out.SourceNamespace = in.SourceNamespace
	out.RestorePoint = in.RestorePoint
	if err := Convert__JobConfig_To_v1beta2_JobConfig(&in.JobConfig, &out.JobConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert__RestoreSpec_To_v1beta2_RestoreSpec is an autogenerated conversion function.
func Convert__RestoreSpec_To_v1beta2_RestoreSpec(in *RestoreSpec, out *v1beta2.RestoreSpec, s conversion.Scope) error {
	return autoConvert__RestoreSpec_To_v1beta2_RestoreSpec(in, out, s)
}

func autoConvert_v1beta2_RestoreSpec_To__RestoreSpec(in *v1beta2.RestoreSpec, out *RestoreSpec, s conversion.Scope) error {
	out.SourceName = in.SourceName
	out.SourceNamespace = in.SourceNamespace
	out.RestorePoint = in.RestorePoint
	if err := Convert_v1beta2_JobConfig_To__JobConfig(&in.JobConfig, &out.JobConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_RestoreSpec_To__RestoreSpec is an autogenerated conversion function.
func Convert_v1beta2_RestoreSpec_To__RestoreSpec(in *v1beta2.RestoreSpec, out *RestoreSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_RestoreSpec_To__RestoreSpec(in, out, s)
}

func autoConvert__ServiceSpecApplyConfiguration_To_v1beta2_ServiceSpecApplyConfiguration(in *ServiceSpecApplyConfiguration, out *v1beta2.ServiceSpecApplyConfiguration, s conversion.Scope) error {
	out.Ports = *(*[]v1.ServicePortApplyConfiguration)(unsafe.Pointer(&in.Ports))
	out.Selector = *(*map[string]string)(unsafe.Pointer(&in.Selector))
	out.ClusterIP = (*string)(unsafe.Pointer(in.ClusterIP))
	out.ClusterIPs = *(*[]string)(unsafe.Pointer(&in.ClusterIPs))
	out.Type = (*corev1.ServiceType)(unsafe.Pointer(in.Type))
	out.ExternalIPs = *(*[]string)(unsafe.Pointer(&in.ExternalIPs))
	out.SessionAffinity = (*corev1.ServiceAffinity)(unsafe.Pointer(in.SessionAffinity))
	out.LoadBalancerIP = (*string)(unsafe.Pointer(in.LoadBalancerIP))
	out.LoadBalancerSourceRanges = *(*[]string)(unsafe.Pointer(&in.LoadBalancerSourceRanges))
	out.ExternalName = (*string)(unsafe.Pointer(in.ExternalName))
	out.ExternalTrafficPolicy = (*corev1.ServiceExternalTrafficPolicyType)(unsafe.Pointer(in.ExternalTrafficPolicy))
	out.HealthCheckNodePort = (*int32)(unsafe.Pointer(in.HealthCheckNodePort))
	out.PublishNotReadyAddresses = (*bool)(unsafe.Pointer(in.PublishNotReadyAddresses))
	out.SessionAffinityConfig = (*v1.SessionAffinityConfigApplyConfiguration)(unsafe.Pointer(in.SessionAffinityConfig))
	out.IPFamilies = *(*[]corev1.IPFamily)(unsafe.Pointer(&in.IPFamilies))
	out.IPFamilyPolicy = (*corev1.IPFamilyPolicy)(unsafe.Pointer(in.IPFamilyPolicy))
	out.AllocateLoadBalancerNodePorts = (*bool)(unsafe.Pointer(in.AllocateLoadBalancerNodePorts))
	out.LoadBalancerClass = (*string)(unsafe.Pointer(in.LoadBalancerClass))
	out.InternalTrafficPolicy = (*corev1.ServiceInternalTrafficPolicyType)(unsafe.Pointer(in.InternalTrafficPolicy))
	return nil
}

// Convert__ServiceSpecApplyConfiguration_To_v1beta2_ServiceSpecApplyConfiguration is an autogenerated conversion function.
func Convert__ServiceSpecApplyConfiguration_To_v1beta2_ServiceSpecApplyConfiguration(in *ServiceSpecApplyConfiguration, out *v1beta2.ServiceSpecApplyConfiguration, s conversion.Scope) error {
	return autoConvert__ServiceSpecApplyConfiguration_To_v1beta2_ServiceSpecApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_ServiceSpecApplyConfiguration_To__ServiceSpecApplyConfiguration(in *v1beta2.ServiceSpecApplyConfiguration, out *ServiceSpecApplyConfiguration, s conversion.Scope) error {
	out.Ports = *(*[]v1.ServicePortApplyConfiguration)(unsafe.Pointer(&in.Ports))
	out.Selector = *(*map[string]string)(unsafe.Pointer(&in.Selector))
	out.ClusterIP = (*string)(unsafe.Pointer(in.ClusterIP))
	out.ClusterIPs = *(*[]string)(unsafe.Pointer(&in.ClusterIPs))
	out.Type = (*corev1.ServiceType)(unsafe.Pointer(in.Type))
	out.ExternalIPs = *(*[]string)(unsafe.Pointer(&in.ExternalIPs))
	out.SessionAffinity = (*corev1.ServiceAffinity)(unsafe.Pointer(in.SessionAffinity))
	out.LoadBalancerIP = (*string)(unsafe.Pointer(in.LoadBalancerIP))
	out.LoadBalancerSourceRanges = *(*[]string)(unsafe.Pointer(&in.LoadBalancerSourceRanges))
	out.ExternalName = (*string)(unsafe.Pointer(in.ExternalName))
	out.ExternalTrafficPolicy = (*corev1.ServiceExternalTrafficPolicyType)(unsafe.Pointer(in.ExternalTrafficPolicy))
	out.HealthCheckNodePort = (*int32)(unsafe.Pointer(in.HealthCheckNodePort))
	out.PublishNotReadyAddresses = (*bool)(unsafe.Pointer(in.PublishNotReadyAddresses))
	out.SessionAffinityConfig = (*v1.SessionAffinityConfigApplyConfiguration)(unsafe.Pointer(in.SessionAffinityConfig))
	out.IPFamilies = *(*[]corev1.IPFamily)(unsafe.Pointer(&in.IPFamilies))
	out.IPFamilyPolicy = (*corev1.IPFamilyPolicy)(unsafe.Pointer(in.IPFamilyPolicy))
	out.AllocateLoadBalancerNodePorts = (*bool)(unsafe.Pointer(in.AllocateLoadBalancerNodePorts))
	out.LoadBalancerClass = (*string)(unsafe.Pointer(in.LoadBalancerClass))
	out.InternalTrafficPolicy = (*corev1.ServiceInternalTrafficPolicyType)(unsafe.Pointer(in.InternalTrafficPolicy))
	return nil
}

// Convert_v1beta2_ServiceSpecApplyConfiguration_To__ServiceSpecApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_ServiceSpecApplyConfiguration_To__ServiceSpecApplyConfiguration(in *v1beta2.ServiceSpecApplyConfiguration, out *ServiceSpecApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_ServiceSpecApplyConfiguration_To__ServiceSpecApplyConfiguration(in, out, s)
}

func autoConvert__ServiceTemplate_To_v1beta2_ServiceTemplate(in *ServiceTemplate, out *v1beta2.ServiceTemplate, s conversion.Scope) error {
	if err := Convert__ObjectMeta_To_v1beta2_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	out.Spec = (*v1beta2.ServiceSpecApplyConfiguration)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert__ServiceTemplate_To_v1beta2_ServiceTemplate is an autogenerated conversion function.
func Convert__ServiceTemplate_To_v1beta2_ServiceTemplate(in *ServiceTemplate, out *v1beta2.ServiceTemplate, s conversion.Scope) error {
	return autoConvert__ServiceTemplate_To_v1beta2_ServiceTemplate(in, out, s)
}

func autoConvert_v1beta2_ServiceTemplate_To__ServiceTemplate(in *v1beta2.ServiceTemplate, out *ServiceTemplate, s conversion.Scope) error {
	if err := Convert_v1beta2_ObjectMeta_To__ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	out.Spec = (*ServiceSpecApplyConfiguration)(unsafe.Pointer(in.Spec))
	return nil
}

// Convert_v1beta2_ServiceTemplate_To__ServiceTemplate is an autogenerated conversion function.
func Convert_v1beta2_ServiceTemplate_To__ServiceTemplate(in *v1beta2.ServiceTemplate, out *ServiceTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_ServiceTemplate_To__ServiceTemplate(in, out, s)
}

func autoConvert__VolumeApplyConfiguration_To_v1beta2_VolumeApplyConfiguration(in *VolumeApplyConfiguration, out *v1beta2.VolumeApplyConfiguration, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.VolumeSourceApplyConfiguration = in.VolumeSourceApplyConfiguration
	return nil
}

// Convert__VolumeApplyConfiguration_To_v1beta2_VolumeApplyConfiguration is an autogenerated conversion function.
func Convert__VolumeApplyConfiguration_To_v1beta2_VolumeApplyConfiguration(in *VolumeApplyConfiguration, out *v1beta2.VolumeApplyConfiguration, s conversion.Scope) error {
	return autoConvert__VolumeApplyConfiguration_To_v1beta2_VolumeApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_VolumeApplyConfiguration_To__VolumeApplyConfiguration(in *v1beta2.VolumeApplyConfiguration, out *VolumeApplyConfiguration, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.VolumeSourceApplyConfiguration = in.VolumeSourceApplyConfiguration
	return nil
}

// Convert_v1beta2_VolumeApplyConfiguration_To__VolumeApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_VolumeApplyConfiguration_To__VolumeApplyConfiguration(in *v1beta2.VolumeApplyConfiguration, out *VolumeApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_VolumeApplyConfiguration_To__VolumeApplyConfiguration(in, out, s)
}

func autoConvert__VolumeMountApplyConfiguration_To_v1beta2_VolumeMountApplyConfiguration(in *VolumeMountApplyConfiguration, out *v1beta2.VolumeMountApplyConfiguration, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ReadOnly = (*bool)(unsafe.Pointer(in.ReadOnly))
	out.MountPath = (*string)(unsafe.Pointer(in.MountPath))
	out.SubPath = (*string)(unsafe.Pointer(in.SubPath))
	out.MountPropagation = (*corev1.MountPropagationMode)(unsafe.Pointer(in.MountPropagation))
	out.SubPathExpr = (*string)(unsafe.Pointer(in.SubPathExpr))
	return nil
}

// Convert__VolumeMountApplyConfiguration_To_v1beta2_VolumeMountApplyConfiguration is an autogenerated conversion function.
func Convert__VolumeMountApplyConfiguration_To_v1beta2_VolumeMountApplyConfiguration(in *VolumeMountApplyConfiguration, out *v1beta2.VolumeMountApplyConfiguration, s conversion.Scope) error {
	return autoConvert__VolumeMountApplyConfiguration_To_v1beta2_VolumeMountApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_VolumeMountApplyConfiguration_To__VolumeMountApplyConfiguration(in *v1beta2.VolumeMountApplyConfiguration, out *VolumeMountApplyConfiguration, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ReadOnly = (*bool)(unsafe.Pointer(in.ReadOnly))
	out.MountPath = (*string)(unsafe.Pointer(in.MountPath))
	out.SubPath = (*string)(unsafe.Pointer(in.SubPath))
	out.MountPropagation = (*corev1.MountPropagationMode)(unsafe.Pointer(in.MountPropagation))
	out.SubPathExpr = (*string)(unsafe.Pointer(in.SubPathExpr))
	return nil
}

// Convert_v1beta2_VolumeMountApplyConfiguration_To__VolumeMountApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_VolumeMountApplyConfiguration_To__VolumeMountApplyConfiguration(in *v1beta2.VolumeMountApplyConfiguration, out *VolumeMountApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_VolumeMountApplyConfiguration_To__VolumeMountApplyConfiguration(in, out, s)
}

func autoConvert__VolumeSourceApplyConfiguration_To_v1beta2_VolumeSourceApplyConfiguration(in *VolumeSourceApplyConfiguration, out *v1beta2.VolumeSourceApplyConfiguration, s conversion.Scope) error {
	out.HostPath = (*v1.HostPathVolumeSourceApplyConfiguration)(unsafe.Pointer(in.HostPath))
	out.EmptyDir = (*v1.EmptyDirVolumeSourceApplyConfiguration)(unsafe.Pointer(in.EmptyDir))
	out.GCEPersistentDisk = (*v1.GCEPersistentDiskVolumeSourceApplyConfiguration)(unsafe.Pointer(in.GCEPersistentDisk))
	out.AWSElasticBlockStore = (*v1.AWSElasticBlockStoreVolumeSourceApplyConfiguration)(unsafe.Pointer(in.AWSElasticBlockStore))
	out.GitRepo = (*v1.GitRepoVolumeSourceApplyConfiguration)(unsafe.Pointer(in.GitRepo))
	out.Secret = (*v1.SecretVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Secret))
	out.NFS = (*v1.NFSVolumeSourceApplyConfiguration)(unsafe.Pointer(in.NFS))
	out.ISCSI = (*v1.ISCSIVolumeSourceApplyConfiguration)(unsafe.Pointer(in.ISCSI))
	out.Glusterfs = (*v1.GlusterfsVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Glusterfs))
	out.PersistentVolumeClaim = (*v1.PersistentVolumeClaimVolumeSourceApplyConfiguration)(unsafe.Pointer(in.PersistentVolumeClaim))
	out.RBD = (*v1.RBDVolumeSourceApplyConfiguration)(unsafe.Pointer(in.RBD))
	out.FlexVolume = (*v1.FlexVolumeSourceApplyConfiguration)(unsafe.Pointer(in.FlexVolume))
	out.Cinder = (*v1.CinderVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Cinder))
	out.CephFS = (*v1.CephFSVolumeSourceApplyConfiguration)(unsafe.Pointer(in.CephFS))
	out.Flocker = (*v1.FlockerVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Flocker))
	out.DownwardAPI = (*v1.DownwardAPIVolumeSourceApplyConfiguration)(unsafe.Pointer(in.DownwardAPI))
	out.FC = (*v1.FCVolumeSourceApplyConfiguration)(unsafe.Pointer(in.FC))
	out.AzureFile = (*v1.AzureFileVolumeSourceApplyConfiguration)(unsafe.Pointer(in.AzureFile))
	out.ConfigMap = (*v1.ConfigMapVolumeSourceApplyConfiguration)(unsafe.Pointer(in.ConfigMap))
	out.VsphereVolume = (*v1.VsphereVirtualDiskVolumeSourceApplyConfiguration)(unsafe.Pointer(in.VsphereVolume))
	out.Quobyte = (*v1.QuobyteVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Quobyte))
	out.AzureDisk = (*v1.AzureDiskVolumeSourceApplyConfiguration)(unsafe.Pointer(in.AzureDisk))
	out.PhotonPersistentDisk = (*v1.PhotonPersistentDiskVolumeSourceApplyConfiguration)(unsafe.Pointer(in.PhotonPersistentDisk))
	out.Projected = (*v1.ProjectedVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Projected))
	out.PortworxVolume = (*v1.PortworxVolumeSourceApplyConfiguration)(unsafe.Pointer(in.PortworxVolume))
	out.ScaleIO = (*v1.ScaleIOVolumeSourceApplyConfiguration)(unsafe.Pointer(in.ScaleIO))
	out.StorageOS = (*v1.StorageOSVolumeSourceApplyConfiguration)(unsafe.Pointer(in.StorageOS))
	out.CSI = (*v1.CSIVolumeSourceApplyConfiguration)(unsafe.Pointer(in.CSI))
	out.Ephemeral = (*v1.EphemeralVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Ephemeral))
	return nil
}

// Convert__VolumeSourceApplyConfiguration_To_v1beta2_VolumeSourceApplyConfiguration is an autogenerated conversion function.
func Convert__VolumeSourceApplyConfiguration_To_v1beta2_VolumeSourceApplyConfiguration(in *VolumeSourceApplyConfiguration, out *v1beta2.VolumeSourceApplyConfiguration, s conversion.Scope) error {
	return autoConvert__VolumeSourceApplyConfiguration_To_v1beta2_VolumeSourceApplyConfiguration(in, out, s)
}

func autoConvert_v1beta2_VolumeSourceApplyConfiguration_To__VolumeSourceApplyConfiguration(in *v1beta2.VolumeSourceApplyConfiguration, out *VolumeSourceApplyConfiguration, s conversion.Scope) error {
	out.HostPath = (*v1.HostPathVolumeSourceApplyConfiguration)(unsafe.Pointer(in.HostPath))
	out.EmptyDir = (*v1.EmptyDirVolumeSourceApplyConfiguration)(unsafe.Pointer(in.EmptyDir))
	out.GCEPersistentDisk = (*v1.GCEPersistentDiskVolumeSourceApplyConfiguration)(unsafe.Pointer(in.GCEPersistentDisk))
	out.AWSElasticBlockStore = (*v1.AWSElasticBlockStoreVolumeSourceApplyConfiguration)(unsafe.Pointer(in.AWSElasticBlockStore))
	out.GitRepo = (*v1.GitRepoVolumeSourceApplyConfiguration)(unsafe.Pointer(in.GitRepo))
	out.Secret = (*v1.SecretVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Secret))
	out.NFS = (*v1.NFSVolumeSourceApplyConfiguration)(unsafe.Pointer(in.NFS))
	out.ISCSI = (*v1.ISCSIVolumeSourceApplyConfiguration)(unsafe.Pointer(in.ISCSI))
	out.Glusterfs = (*v1.GlusterfsVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Glusterfs))
	out.PersistentVolumeClaim = (*v1.PersistentVolumeClaimVolumeSourceApplyConfiguration)(unsafe.Pointer(in.PersistentVolumeClaim))
	out.RBD = (*v1.RBDVolumeSourceApplyConfiguration)(unsafe.Pointer(in.RBD))
	out.FlexVolume = (*v1.FlexVolumeSourceApplyConfiguration)(unsafe.Pointer(in.FlexVolume))
	out.Cinder = (*v1.CinderVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Cinder))
	out.CephFS = (*v1.CephFSVolumeSourceApplyConfiguration)(unsafe.Pointer(in.CephFS))
	out.Flocker = (*v1.FlockerVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Flocker))
	out.DownwardAPI = (*v1.DownwardAPIVolumeSourceApplyConfiguration)(unsafe.Pointer(in.DownwardAPI))
	out.FC = (*v1.FCVolumeSourceApplyConfiguration)(unsafe.Pointer(in.FC))
	out.AzureFile = (*v1.AzureFileVolumeSourceApplyConfiguration)(unsafe.Pointer(in.AzureFile))
	out.ConfigMap = (*v1.ConfigMapVolumeSourceApplyConfiguration)(unsafe.Pointer(in.ConfigMap))
	out.VsphereVolume = (*v1.VsphereVirtualDiskVolumeSourceApplyConfiguration)(unsafe.Pointer(in.VsphereVolume))
	out.Quobyte = (*v1.QuobyteVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Quobyte))
	out.AzureDisk = (*v1.AzureDiskVolumeSourceApplyConfiguration)(unsafe.Pointer(in.AzureDisk))
	out.PhotonPersistentDisk = (*v1.PhotonPersistentDiskVolumeSourceApplyConfiguration)(unsafe.Pointer(in.PhotonPersistentDisk))
	out.Projected = (*v1.ProjectedVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Projected))
	out.PortworxVolume = (*v1.PortworxVolumeSourceApplyConfiguration)(unsafe.Pointer(in.PortworxVolume))
	out.ScaleIO = (*v1.ScaleIOVolumeSourceApplyConfiguration)(unsafe.Pointer(in.ScaleIO))
	out.StorageOS = (*v1.StorageOSVolumeSourceApplyConfiguration)(unsafe.Pointer(in.StorageOS))
	out.CSI = (*v1.CSIVolumeSourceApplyConfiguration)(unsafe.Pointer(in.CSI))
	out.Ephemeral = (*v1.EphemeralVolumeSourceApplyConfiguration)(unsafe.Pointer(in.Ephemeral))
	return nil
}

// Convert_v1beta2_VolumeSourceApplyConfiguration_To__VolumeSourceApplyConfiguration is an autogenerated conversion function.
func Convert_v1beta2_VolumeSourceApplyConfiguration_To__VolumeSourceApplyConfiguration(in *v1beta2.VolumeSourceApplyConfiguration, out *VolumeSourceApplyConfiguration, s conversion.Scope) error {
	return autoConvert_v1beta2_VolumeSourceApplyConfiguration_To__VolumeSourceApplyConfiguration(in, out, s)
}
