name: Setup Aqua
description: Install Aqua CLI
runs:
  using: composite
  steps:
    - name: Restore aqua cache
      uses: actions/cache/restore@v4
      with:
        path: ~/.local/share/aquaproj-aqua
        key: v1-aqua-installer-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('aqua.yaml') }}
        restore-keys: |
          v1-aqua-installer-${{ runner.os }}-${{ runner.arch }}-

    - name: Install aqua
      uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
      with:
        aqua_version: v2.53.11
        working_directory: ${{ inputs.working_directory }}
        # aqua-installer runs aqua with -l option by default, so packages that aren't run in the workflow aren't cached.
        aqua_opts: ""

    - name: Save aqua cache
      if: github.ref_name == 'main'
      uses: actions/cache/save@v4
      with:
        path: ~/.local/share/aquaproj-aqua
        key: v1-aqua-installer-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('aqua.yaml') }}
