name: Integration tests with MySQL

on:
  workflow_call:
    inputs:
      mysql-version:
        required: true
        type: string

jobs:
  dbtest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: make setup
      - run: make test-bkop MYSQL_VERSION=${{ inputs.mysql-version }}
      - run: make test-dbop MYSQL_VERSION=${{ inputs.mysql-version }}
