name: End-to-End Tests

on:
  workflow_call:
    inputs:
      mysql-version:
        required: true
        type: string
      k8s-version:
        required: true
        type: string

jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: |
          swapon > swapon.txt
          sudo swapoff -a
          cat swapon.txt | tail -n+2 | awk '$2=="file" {print $1}' | sudo xargs --no-run-if-empty rm
      - run: sudo mkdir /mnt/local-path-provisioner0 /mnt/local-path-provisioner1 /mnt/local-path-provisioner2
      - run: make start KUBERNETES_VERSION=${{ inputs.k8s-version }} MYSQL_VERSION=${{ inputs.mysql-version }} KIND_CONFIG=kind-config_actions.yaml
        working-directory: e2e
      - run: make test
        working-directory: e2e
      - run: make logs
        working-directory: e2e
        if: always()
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs-${{ inputs.k8s-version }}-${{ inputs.mysql-version }}.tar.gz
          path: e2e/logs.tar.gz
